services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpassword
      POSTGRES_DB: testdatabase
    volumes:
      - ./database/db-init.sql:/docker-entrypoint-initdb.d/db-init.sql
    ports:  
      - "5432:5432"
  backend:
    build: ./backend
    #image: myapp:latest
    environment:
      APP_ENV: development
      APP_DEBUG: true
      # DB_HOST: db
      # DB_PORT: 5432
      DB_USER: testuser
      DB_PASSWORD: testpassword
      DB_NAME: testdatabase
    ports:
      - "5000:5000"
    depends_on:
      - db
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: http://localhost:5000
    depends_on:
      - backend
